### PR TITLE
Remove check_retriever_availability function in  onload

### PR DESCRIPTION
**Pull request by henrykironde**

### CODE REVIEW

**Comment by ethanwhite** [comment]
Where you capable of replicated the NOTE and did this remove the error for you? This change reverts the functionality. I can try to work around it (I'd already worked around one version of this before) but only if we can replicated the NOTE effectively.

**Comment by ethanwhite** [comment]
Or we could just pull the functionality for now if we just want to get the release out the door. I'm happy either way.

**Comment by henrykironde** [comment]
Just got a response from the windows server. looks like this works well with out any notes 👍 

https://win-builder.r-project.org/lX4QLhW7dCfl/

**Comment by henrykironde** [comment]
Do we want to keep that function `check_retriever_availability`?

**Comment by henrykironde** [comment]
Replaced by#244

**Pull request closed without merging**
