### PR TITLE
Order affiliations by use

### PR DESCRIPTION
**Pull request by ethanwhite**
This orders the affiliations to line up with the order of names in the author list. Delhi Technological University was removed because it didn't appear to be associated with anyone, but please check to ensure that is correct. Also please give this is careful check to make sure I didn't make any mistakes in the re-ordering since this is important to get precisely right.

### CODE REVIEW

**Comment by henrykironde** [comment]
Yes Delhi was supposed to have been for the the recent intern.

**Comment by ethanwhite** [comment]
So are we missing a person and if not who should that affiliation be associated with (it wasn't associated with anyone previously)?

**Comment by henrykironde** [comment]
The student ended up not contributing to the project.

**Comment by ethanwhite** [comment]
Ah, got it, sorry for misunderstanding.

**Comment by henrykironde** [comment]
Thanks for the PR @ethanwhite , I think you add 11 and 12 which are the same. Otherwise the rest look good.

**Comment by ethanwhite** [comment]
Oops, thanks for the catch. 12 is meant to be Biodiversity Institute not Informatics. Fixed.

**Pull request merged**
