### PR TITLE
Update rdataretriever to include latest changes in retriever

### PR DESCRIPTION
**Pull request by apoorvaeternity**
Updates rdataretriever to include new features added in retriever.

### CODE REVIEW

**Comment by henrykironde** [comment]
Thanks @apoorvaeternity for these changes, Like you said, we shall have to clean up the code and provide good doc strings and update the docs. 
Yes it is hard to get reticulate up and running smoothly, especially the fact that there are current bugs in reticulate. 

When cleaning up, we could just create one new commit,  It is okey to overwrite my commits.

**Comment by apoorvaeternity** [comment]
@henrykironde 
Okay, I will check the code to find places where we can improve and update the doc strings.
One question - Why do we have two functions `datasets` and `dataset_names` in `rdataretriever`?

**Comment by henrykironde** [comment]
> Why do we have two functions datasets and dataset_names in rdataretriever?

One is Deprecated. It was the old way of getting the same results as `retriever ls` but we changed the function name. We need to keep both the old and new to take care of backward compatibility.

I have also updated the commit log function in the retriever to return the log object so that we can use it in other tools to print the log info

**Comment by henrykironde** [comment]
Hi @apoorvaeternity, I have added some functionality to your work. I l know you are busy but whenever you get time, test the Provence work with the new additions from https://github.com/apoorvaeternity/rdataretriever/pull/1. If you think they are good merge that PR. In case you want me to change some things, I am more than happy to 👍 . A big thank you for this work once again

**Pull request merged**
