### PR TITLE
Add functionality to reset a specific dataset

### PR DESCRIPTION
**Pull request by harshitbansal05**
This pull request aims to fix: #180. It adds the functionality to reset a specific dataset similar to as in the python module.

### CODE REVIEW

**Comment by henrykironde** [comment]
Use the retriever interface to reset

**Comment by harshitbansal05** [comment]
@henrykironde I have made the specified changes.

**Comment by harshitbansal05** [comment]
@henrykironde is it fine now?

**Comment by henrykironde** [comment]
Looks fine, I am trying to come up with some tests for this. It will follow the same procedure as the tests we want to add to retriever when we use reset.

**Comment by henrykironde** [comment]
Thanks @harshitbansal05, for the patch.

**Pull request merged**
