### PR TITLE
Fetch function update

### PR DESCRIPTION
**Pull request by pranita-s**
I have made changes to the fetch function. It works as follows:

fetchupdated

@ethanwhite @henrykironde Please review this PR.

### CODE REVIEW

**Comment by ethanwhite** [comment]
Thanks finding and for putting together a fix for this @pranita-s!

As discussed in #131 and https://github.com/weecology/retriever/issues/1101 this is a bug in the core retriever that is lower casing the directory name. That said, I think we should go ahead and patch this here. I'd prefer to avoid using `setwd` if possible, so what doing something like:

```
# Create an all lower case temporary directory to address https://github.com/weecology/retriever/issues/1101
temp_path = tolower(tempdir())
dir.create(temp_path)
```

**Comment by pranita-s** [comment]
@ethanwhite Its perfect as changing directory is not necessary!

**Comment by henrykironde** [comment]
LGTM

**Comment by ethanwhite** [comment]
Thanks @pranita-s!

**Comment by ethanwhite** [comment]
Welcome to the team!

screenshot from 2018-03-01 09-06-23

**Pull request merged**
