### PR TITLE
Use reticulate to wrap Python package instead of the CLI

### PR DESCRIPTION
**Pull request by henrykironde**

### CODE REVIEW

**Comment by henrykironde** [comment]
😁

**Comment by ethanwhite** [comment]
Congratulations Henry!!!

This all looks great. There's a bunch of debugging comments that I'm sure you're already planning on cleaning up. The one other thing I might consider is moving these two lines:

```
install.packages(".", repos = NULL, type="source")
devtools::test()
```

out of `install-packages.R`.

I was originally confused by how things were working since reading `.travis.yml` it felt like the only thing you did has install the package and not run the tests. Having these lines either individually in travis or in their own file/files might make it clearer that travis is first installing dependencies and then installing the version of rdataretriever to be tested, and then running the tests.

Awesome work - I know this has been a tough one to get working and the solution you've come up with is *really* nice!

**Comment by henrykironde** [comment]
ref #154

**Comment by henrykironde** [comment]
@ethanwhite, whenever you get time(not Urgent), have a second look at this, I cleaned it up. The reason for install-packages.R was basically to run these two commands
```
install.packages(".", repos = NULL, type="source")
devtools::test()
```
We are using Pacman to make sure that we load the libraries used only when testing and if the library is not found install it. We can discus this again and I could try some better arrangements.

**Comment by ethanwhite** [comment]
Looks great! I'm very excited to have this in.

A huge thanks to @pranita-s for all her work this summer converting the package over to `reticulate` and also a big thanks to @henrykironde for his mentorship during that process and for creating a testing system that worked effectively for the `reticulate` based approach.

**Pull request merged**
